[theme]
# Cor principal (dos botões e links)
primaryColor="#00adb5"

# Cor do fundo principal da página
backgroundColor="#393e46"

# Cor do fundo secundário (da barra lateral, se tiver)
secondaryBackgroundColor="#222831"

# Cor do texto
textColor="#eeeeee"
